# reactor(1) completion -- generated by `reactor completion bash`

_reactor_ids() {
    reactor __complete "$1" 2>/dev/null
}

_reactor() {
    local cur prev words cword
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    local top="doctor registry services tools toolsets skills install refresh diff-config overwrite-config state setup completion"

    # Walk the words before `cur`, skipping global flags and their values, to
    # find the command and (if any) its subcommand.
    local cmd="" sub="" i=1 w
    while ((i < COMP_CWORD)); do
        w=${COMP_WORDS[i]}
        case $w in
            --format) ((i++)) ;;
            -*) ;;
            *)
                if [[ -z $cmd ]]; then cmd=$w; elif [[ -z $sub ]]; then sub=$w; fi
                ;;
        esac
        ((i++))
    done

    if [[ -z $cmd ]]; then
        COMPREPLY=($(compgen -W "$top" -- "$cur"))
        return
    fi

    case $cmd in
        tools)
            if [[ -z $sub ]]; then
                COMPREPLY=($(compgen -W "list show enable disable reset" -- "$cur"))
            elif [[ $sub == show || $sub == enable || $sub == disable || $sub == reset ]]; then
                COMPREPLY=($(compgen -W "$(_reactor_ids tools)" -- "$cur"))
            fi
            ;;
        toolsets)
            if [[ -z $sub ]]; then
                COMPREPLY=($(compgen -W "list show enable disable" -- "$cur"))
            elif [[ $sub == show || $sub == enable || $sub == disable ]]; then
                COMPREPLY=($(compgen -W "$(_reactor_ids toolsets)" -- "$cur"))
            fi
            ;;
        skills)
            if [[ -z $sub ]]; then
                COMPREPLY=($(compgen -W "list show fetch" -- "$cur"))
            elif [[ $sub == show || $sub == fetch ]]; then
                COMPREPLY=($(compgen -W "$(_reactor_ids tools)" -- "$cur"))
            fi
            ;;
        install)
            COMPREPLY=($(compgen -W "all $(_reactor_ids tools)" -- "$cur"))
            ;;
        completion)
            [[ -z $sub ]] && COMPREPLY=($(compgen -W "bash zsh fish" -- "$cur"))
            ;;
        diff-config|overwrite-config)
            [[ $prev == --file ]] && COMPREPLY=($(compgen -W "tools toolsets" -- "$cur"))
            ;;
    esac
}
complete -F _reactor reactor
