#compdef reactor
# reactor(1) completion -- generated by `reactor completion zsh`
#
# Reads $words/$CURRENT directly rather than driving zsh's `_arguments` state
# machine: reactor's own subcommand tree is only two levels deep, so a case
# statement over the words already on the line is simpler than a grammar for
# it, and there is no `_arguments` spec to get subtly wrong.

_reactor_ids() {
    # $1 kind ("tools"|"toolsets"), $2 description, $3... extra literal values.
    local -a ids extra
    ids=(${(f)"$(reactor __complete "$1" 2>/dev/null)"})
    extra=("${@:3}")
    _describe -t "$1" "$2" ids
    (( $#extra )) && _values "$2" $extra
}

_reactor() {
    local cmd sub
    (( CURRENT >= 2 )) && cmd=${words[2]}
    (( CURRENT >= 3 )) && sub=${words[3]}

    if (( CURRENT == 2 )); then
        local -a top_cmds
        top_cmds=(
            'doctor:what is present, what is not, how to get it'
            'registry:the block injected into the system prompt'
            'services:what is running right now'
            'tools:catalogue queries and activation'
            'toolsets:named groups of tools'
            'skills:upstream skills REactor has fetched'
            'install:install a missing tool'
            'refresh:drop the probe cache and re-probe'
            'diff-config:diff shipped config against yours'
            'overwrite-config:force-replace yours with the shipped copy'
            'state:current activation state'
            'setup:seed ~/.reactor/, fetch skills, install completions'
            'completion:print a shell completion script'
        )
        _describe -t commands 'reactor command' top_cmds
        return
    fi

    case $cmd in
        tools)
            if (( CURRENT == 3 )); then
                _values 'subcommand' list show enable disable reset
            elif [[ $sub == (show|enable|disable|reset) ]]; then
                _reactor_ids tools 'tool id'
            fi
            ;;
        toolsets)
            if (( CURRENT == 3 )); then
                _values 'subcommand' list show enable disable
            elif [[ $sub == (show|enable|disable) ]]; then
                _reactor_ids toolsets 'toolset id'
            fi
            ;;
        skills)
            if (( CURRENT == 3 )); then
                _values 'subcommand' list show fetch
            elif [[ $sub == (show|fetch) ]]; then
                _reactor_ids tools 'tool id'
            fi
            ;;
        install)
            _reactor_ids tools 'tool id' all
            ;;
        completion)
            (( CURRENT == 3 )) && _values 'shell' bash zsh fish
            ;;
        diff-config|overwrite-config)
            [[ ${words[CURRENT-1]} == --file ]] && _values 'file' tools toolsets
            ;;
    esac
}

_reactor "$@"
