# reactor(1) completion -- generated by `reactor completion fish`

function __reactor_ids
    reactor __complete $argv[1] 2>/dev/null
end

set -l top_cmds doctor registry services tools toolsets skills install refresh diff-config overwrite-config state setup completion

complete -c reactor -f
complete -c reactor -n __fish_use_subcommand -a doctor -d 'what is present, what is not, how to get it'
complete -c reactor -n __fish_use_subcommand -a registry -d 'the block injected into the system prompt'
complete -c reactor -n __fish_use_subcommand -a services -d 'what is running right now'
complete -c reactor -n __fish_use_subcommand -a tools -d 'catalogue queries and activation'
complete -c reactor -n __fish_use_subcommand -a toolsets -d 'named groups of tools'
complete -c reactor -n __fish_use_subcommand -a skills -d 'upstream skills REactor has fetched'
complete -c reactor -n __fish_use_subcommand -a install -d 'install a missing tool'
complete -c reactor -n __fish_use_subcommand -a refresh -d 'drop the probe cache and re-probe'
complete -c reactor -n __fish_use_subcommand -a diff-config -d 'diff shipped config against yours'
complete -c reactor -n __fish_use_subcommand -a overwrite-config -d 'force-replace yours with the shipped copy'
complete -c reactor -n __fish_use_subcommand -a state -d 'current activation state'
complete -c reactor -n __fish_use_subcommand -a setup -d 'seed ~/.reactor/, fetch skills, install completions'
complete -c reactor -n __fish_use_subcommand -a completion -d 'print a shell completion script'

complete -c reactor -n '__fish_seen_subcommand_from tools; and not __fish_seen_subcommand_from list show enable disable reset' -a 'list show enable disable reset'
complete -c reactor -n '__fish_seen_subcommand_from tools; and __fish_seen_subcommand_from show enable disable reset' -a '(__reactor_ids tools)'

complete -c reactor -n '__fish_seen_subcommand_from toolsets; and not __fish_seen_subcommand_from list show enable disable' -a 'list show enable disable'
complete -c reactor -n '__fish_seen_subcommand_from toolsets; and __fish_seen_subcommand_from show enable disable' -a '(__reactor_ids toolsets)'

complete -c reactor -n '__fish_seen_subcommand_from skills; and not __fish_seen_subcommand_from list show fetch' -a 'list show fetch'
complete -c reactor -n '__fish_seen_subcommand_from skills; and __fish_seen_subcommand_from show fetch' -a '(__reactor_ids tools)'

complete -c reactor -n '__fish_seen_subcommand_from install' -a 'all (__reactor_ids tools)'
complete -c reactor -n '__fish_seen_subcommand_from completion' -a 'bash zsh fish'
complete -c reactor -n '__fish_seen_subcommand_from diff-config overwrite-config' -l file -rf -a 'tools toolsets'
